(cl:defpackage linear_mpc-srv
  (:use )
  (:export
   "SETPOSE"
   "<SETPOSE-REQUEST>"
   "SETPOSE-REQUEST"
   "<SETPOSE-RESPONSE>"
   "SETPOSE-RESPONSE"
   "SETTRAJECTORY"
   "<SETTRAJECTORY-REQUEST>"
   "SETTRAJECTORY-REQUEST"
   "<SETTRAJECTORY-RESPONSE>"
   "SETTRAJECTORY-RESPONSE"
  ))

