// Generated by gencpp from file linear_mpc/SetPose.msg
// DO NOT EDIT!


#ifndef LINEAR_MPC_MESSAGE_SETPOSE_H
#define LINEAR_MPC_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <linear_mpc/SetPoseRequest.h>
#include <linear_mpc/SetPoseResponse.h>


namespace linear_mpc
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace linear_mpc


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::linear_mpc::SetPose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::linear_mpc::SetPose&) { return value(); }
};

template<>
struct DataType< ::linear_mpc::SetPose > {
  static const char* value()
  {
    return "linear_mpc/SetPose";
  }

  static const char* value(const ::linear_mpc::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::linear_mpc::SetPoseRequest> should match 
// service_traits::MD5Sum< ::linear_mpc::SetPose > 
template<>
struct MD5Sum< ::linear_mpc::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::linear_mpc::SetPose >::value();
  }
  static const char* value(const ::linear_mpc::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::linear_mpc::SetPoseRequest> should match 
// service_traits::DataType< ::linear_mpc::SetPose > 
template<>
struct DataType< ::linear_mpc::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::linear_mpc::SetPose >::value();
  }
  static const char* value(const ::linear_mpc::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::linear_mpc::SetPoseResponse> should match 
// service_traits::MD5Sum< ::linear_mpc::SetPose > 
template<>
struct MD5Sum< ::linear_mpc::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::linear_mpc::SetPose >::value();
  }
  static const char* value(const ::linear_mpc::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::linear_mpc::SetPoseResponse> should match 
// service_traits::DataType< ::linear_mpc::SetPose > 
template<>
struct DataType< ::linear_mpc::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::linear_mpc::SetPose >::value();
  }
  static const char* value(const ::linear_mpc::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LINEAR_MPC_MESSAGE_SETPOSE_H
